"""
_scenario_params.py
===================
Single source of truth for the declared scenario parameters that appear in
Table 2 of the paper (tab:calibration).

These are NOT estimated from data — they are chosen to reflect hodler
under-representation in young pools (Assumption: hodler under-representation).
The FIFO/Little's-law comparison in the paper is post-hoc validation, not a
calibration criterion.

User-type model
---------------
A single shared mixing weight vector π^est is used for BOTH systems.
Calibrated on Railgun (the more mature pool, ~4 years of data).
Applied to Privacy Pools with the same π but a shorter hodler mean (μ_h^PP)
reflecting the ~445-day observation window (right-censored hodler distribution).

To update the entropy results:
  1. Edit the constants below.
  2. Macros are auto-generated by compute_table2.py (writes macros_generated.tex).
     Run: python scripts/compute_table2.py --output-dir Figures
     Then copy Figures/macros_generated.tex to the paper repo.
  3. If π changes, re-run all entropy scripts (they all import from here):
       python scripts/compute_m2_canonical.py   --rg-data ...
       python scripts/compute_m3_canonical.py   --rg-data ...
       python scripts/compute_pp_m2_addr.py     --source  ...
       python scripts/compute_pp_m3.py          --source  ...
       python scripts/compute_pp_m4.py          --source  ...
"""

import numpy as np

# ── Shared mixing weights π^est (same for RG and PP) ─────────────────────────
# Calibrated on Railgun (the more mature system).
# Components: sprinter / regular / hodler
SHARED_PI = np.array([0.085, 0.461, 0.454])   # sum = 1

# ── Mean holding times μ^est (days) ──────────────────────────────────────────
RG_MU  = np.array([0.09,  8.79,  403.0])   # sprinter / regular / hodler (RG)
PP_MU  = np.array([0.09,  8.79,  246.0])   # PP: μ_h lower due to ~445 d observation window

# ── Convenience aliases (π is shared, μ differs only in hodler component) ────
RG_PI  = SHARED_PI
PP_PI  = SHARED_PI

# Shared observed means from joint CDF fit (μ^{obs}) — right-censored hodler
MU_OBS = np.array([0.09,  8.79,   45.0])   # sprinter / regular / hodler (days)
