
# ── path config (override via env vars BPLEAK_RG_DATA / BPLEAK_PP_DATA / BPLEAK_FIGURES) ──
import sys as _sys; _sys.path.insert(0, str(__import__('pathlib').Path(__file__).parent))
from _paths import RG_DATA as _RG_DATA, PP_DATA as _PP_DATA, FIGURES as _FIGURES
#!/usr/bin/env python3
"""
Fit a 3-component exponential mixture to the Railgun address-reuse delay data,
then write:
  Figures/timing_3mixture_fit.csv          (log-spaced CDF for PGFPlots)
  Figures/timing_3mixture_refit.tex        (ready to \input into cdf_deltas_pdf.tex)

Run from the BehaviouralPrivacyLeakageFC/ directory:
  python3 scripts/fit_3component_mixture.py
"""

import numpy as np
import pandas as pd
from scipy.special import logsumexp
import os, sys

# ── 1. Load raw delay data ────────────────────────────────────────────────────
data_path = _FIGURES / "cdf_deltas_data_full.csv"
df = pd.read_csv(data_path)
x = df["days"].values
x = x[x > 1e-6]          # drop zeros / sub-second noise
n = len(x)
print(f"Loaded {n} positive delay observations from {data_path}")
print(f"  min={x.min():.4f} d  median={np.median(x):.2f} d  max={x.max():.1f} d")

# ── 2. EM algorithm for 3-component exponential mixture ───────────────────────
def em_3exp(x, pi_init, mu_init, n_iter=2000, tol=1e-10):
    pi = np.array(pi_init, dtype=float)
    mu = np.array(mu_init, dtype=float)
    ll_prev = -np.inf
    for it in range(n_iter):
        # E-step: log responsibilities
        log_r = np.column_stack([
            np.log(pi[k]) - np.log(mu[k]) - x / mu[k]
            for k in range(3)
        ])
        log_norm = logsumexp(log_r, axis=1, keepdims=True)
        r = np.exp(log_r - log_norm)

        # M-step
        N_k  = r.sum(axis=0)            # effective counts
        pi   = N_k / n
        mu   = (r * x[:, None]).sum(axis=0) / N_k

        # log-likelihood for convergence check
        ll = log_norm.sum()
        if ll - ll_prev < tol:
            print(f"  EM converged at iteration {it+1},  log-lik = {ll:.4f}")
            break
        ll_prev = ll
    return pi, mu

# Initialise with three qualitatively distinct modes visible in the plot:
#   fast  ~ hours–1 day  (π≈0.15, μ≈0.3 d)
#   mid   ~ weeks        (π≈0.55, μ≈15 d)
#   slow  ~ months       (π≈0.30, μ≈180 d)
pi0 = [0.15, 0.55, 0.30]
mu0 = [0.30, 15.0, 180.0]

print("\nRunning EM (3-component exponential mixture) …")
pi, mu = em_3exp(x, pi0, mu0)

# Sort components by mean (ascending)
order = np.argsort(mu)
pi, mu = pi[order], mu[order]

print(f"\n3-component mixture fit:")
for k in range(3):
    label = ["fast", "medium", "slow"][k]
    print(f"  [{label}]  π = {pi[k]:.4f},  μ = {mu[k]:.4f} d  "
          f"({mu[k]*24:.1f} h  /  {mu[k]/7:.2f} wk  /  {mu[k]/30:.2f} mo)")

# ── 3. Generate log-spaced CDF for PGFPlots ───────────────────────────────────
t_lo = np.log10(max(x.min() * 0.5, 1e-3))
t_hi = np.log10(x.max() * 1.05)
t = np.logspace(t_lo, t_hi, 600)
cdf_vals = sum(pi[k] * (1 - np.exp(-t / mu[k])) for k in range(3))

out_csv = "Figures/timing_3mixture_fit.csv"
pd.DataFrame({"days": t, "cdf": cdf_vals}).to_csv(out_csv, index=False)
print(f"\nWrote {out_csv}  ({len(t)} points)")

# ── 4. Write PGFPlots \addplot snippet ────────────────────────────────────────
# Use the same analytic formula approach as timing_mixture_refit.tex so no
# external CSV is needed (keeps the figure self-contained in TeX).
# CDF(t) = sum_k pi_k * (1 - exp(-t / mu_k))
# In PGFPlots log-axis convention: variable \u = log10(t), so t = 10^\u.

tex_lines = [
    "% Generated by scripts/fit_3component_mixture.py",
    "% 3-component exponential mixture fitted to cdf_deltas_data_full.csv",
    f"% pi = [{pi[0]:.6f}, {pi[1]:.6f}, {pi[2]:.6f}]",
    f"% mu = [{mu[0]:.6f}, {mu[1]:.6f}, {mu[2]:.6f}] days",
    r"\addplot [thick, colorAccent, dotted, no marks,"
    f" domain={t_lo:.4f}:{t_hi:.4f},",
    r"  samples=300, variable=\u]",
    # build the expression: each term pi_k*(1-exp(-10^u / mu_k))
]

terms = " + ".join(
    f"{pi[k]:.10f}*(1-exp(-10^\\u/{mu[k]:.10f}))"
    for k in range(3)
)
tex_lines.append(f"  ({{10^\\u}},{{{terms}}});")
tex_lines.append(r"\addlegendentry{Railgun three-exponential CDF fit}")

out_tex = "Figures/timing_3mixture_refit.tex"
with open(out_tex, "w") as fh:
    fh.write("\n".join(tex_lines) + "\n")
print(f"Wrote {out_tex}")

# ── 5. Quick sanity: compare median from fit vs data ─────────────────────────
from scipy.optimize import brentq
def cdf_fit(t):
    return sum(pi[k] * (1 - np.exp(-t / mu[k])) for k in range(3))

med_fit  = brentq(lambda t: cdf_fit(t) - 0.5, 1e-4, x.max())
med_data = np.median(x)
print(f"\nSanity check:")
print(f"  Median (data) = {med_data:.2f} d  |  Median (fit) = {med_fit:.2f} d")

# Quantile comparisons
for q in [0.10, 0.25, 0.50, 0.75, 0.90]:
    qd = np.quantile(x, q)
    qf = brentq(lambda t: cdf_fit(t) - q, 1e-4, x.max())
    print(f"  p{int(q*100):02d}:  data={qd:.2f} d   fit={qf:.2f} d")
