"""Fit a zero-location exponential to the full archived Railgun delay ECDF.

One row per observed delay, including ties and zero delays. The exponential
mean MLE is the sample mean. The ECDF distance is descriptive, not a
calibrated KS p-value (parameters fitted on these same, dependent pairs).
"""
import csv
import hashlib
import json
import math
from pathlib import Path

# ── path config (override via env vars BPLEAK_RG_DATA / BPLEAK_PP_DATA / BPLEAK_FIGURES) ──
import sys as _sys; _sys.path.insert(0, str(__import__('pathlib').Path(__file__).parent))
from _paths import RG_DATA as _RG_DATA, PP_DATA as _PP_DATA, FIGURES as _FIGURES

def main():
    root = Path(__file__).resolve().parents[1]
    source = root / 'Figures/cdf_deltas_data_full.csv'
    rows = list(csv.DictReader(source.open()))
    times = sorted(float(r['days']) for r in rows)
    if not times or any(not math.isfinite(t) or t < 0 for t in times):
        raise ValueError('Expected finite nonnegative delays')
    n = len(times)
    mean = math.fsum(times) / n
    if mean <= 0:
        raise ValueError('Positive mean required')
    # Validate that the source is a full ranked ECDF, rather than quantiles.
    for i, row in enumerate(rows, 1):
        if abs(float(row['cdf']) - i/n) > 1e-8:
            raise ValueError('Source does not contain full empirical ranks')
    fitted = [-math.expm1(-t/mean) for t in times]
    distance = max(max(i/n-f, f-(i-1)/n)
                   for i, f in enumerate(fitted, 1))
    report = dict(source=str(source.relative_to(root)),
                  sha256=hashlib.sha256(source.read_bytes()).hexdigest(),
                  n=n, zero_delays=sum(t == 0 for t in times),
                  family='exponential', location_days=0,
                  fit='MLE on all full-ECDF rows, including zeros',
                  mean_days=mean, rate_per_day=1/mean,
                  fitted_median_days=mean*math.log(2),
                  empirical_median_days=(times[(n-1)//2]+times[n//2])/2,
                  ecdf_sup_distance=distance,
                  note='In-sample descriptive fit; no KS p-value or funding-time validation.')
    (root/'Figures/timing_exponential_fit.json').write_text(json.dumps(report, indent=2)+'\n')
    (root/'Figures/timing_exponential_fit.tex').write_text(
        '% Generated by scripts/fit_timing_exponential.py; days; location=0.\n'
        '\\addplot [thick, teal!80!black, dashdotted, no marks,\n'
        '  domain=-3:3.176091259, samples=250, variable=\\u]\n'
        f'  ({{10^\\u}},{{1-exp(-10^\\u/{mean:.16g})}});\n'
        '\\addlegendentry{Railgun exponential fit}\n')
    print(json.dumps(report, indent=2))

if __name__ == '__main__':
    main()
