"""Refit the plotted Railgun ECDF; log-time CDF least squares, no truncation.

The fit grid includes the full observed positive delay range. Report a
separate 7--183 day discrepancy without conditioning the ECDF on that range.
This is descriptive in-sample fitting, not a calibrated funding-time prior.
"""
from pathlib import Path

# ── path config (override via env vars BPLEAK_RG_DATA / BPLEAK_PP_DATA / BPLEAK_FIGURES) ──
import sys as _sys; _sys.path.insert(0, str(__import__('pathlib').Path(__file__).parent))
from _paths import RG_DATA as _RG_DATA, PP_DATA as _PP_DATA, FIGURES as _FIGURES
import csv, json, hashlib
import numpy as np
from scipy.optimize import least_squares

root = Path(__file__).resolve().parents[1]
source = _FIGURES / 'cdf_deltas_data_full.csv'
rows = list(csv.DictReader(source.open()))
t = np.sort(np.array([float(r['days']) for r in rows]))
assert np.all(np.isfinite(t)) and np.all(t >= 0)
n = len(t)
assert np.allclose([float(r['cdf']) for r in rows], np.arange(1,n+1)/n)
grid = np.geomspace(max(t[t>0].min(), 0.001), t.max(), 1200)
emp = np.searchsorted(t, grid, side='right')/n
def cdf(x, p):
    weight, m1, m2 = p[0], np.exp(p[1]), np.exp(p[2])
    return weight*(-np.expm1(-x/m1))+(1-weight)*(-np.expm1(-x/m2))
fits = []
for weight in (.1,.3,.6,.9):
    for means in ((.1,20),(.5,50),(3,80),(10,100)):
        fit = least_squares(lambda p:cdf(grid,p)-emp,
            [weight,*np.log(means)], bounds=([0,-12,-12],[1,12,12]),
            max_nfev=3000, ftol=1e-12, xtol=1e-12, gtol=1e-12)
        fits.append(fit)
best = min(fits,key=lambda f:np.sum(f.fun**2))
p=best.x
weight=float(p[0]); m1,m2=np.exp(p[1:])
if m1>m2: m1,m2=m2,m1;weight=1-weight
p=np.array([weight,np.log(m1),np.log(m2)])
old=np.array([.15327449008715566,np.log(.3857548630972364),np.log(59.370035930997695)])
def metrics(params):
    # Exact one-sided ECDF limits at all jumps, plus interval boundaries.
    xs=np.unique(np.concatenate((t, [7.,183.])))
    lo=np.searchsorted(t,xs,side='left')/n
    hi=np.searchsorted(t,xs,side='right')/n
    y=cdf(xs,params); err=np.maximum(abs(y-lo),abs(y-hi))
    select=(xs>=7)&(xs<=183)
    return dict(max_cdf_error=float(err.max()),
        max_cdf_error_7_183=float(err[select].max()),
        log_grid_rmse=float(np.sqrt(np.mean((cdf(grid,params)-emp)**2))))
result=dict(n=n,sha256=hashlib.sha256(source.read_bytes()).hexdigest(),
    source=str(source.relative_to(root)),
    objective='unweighted CDF least squares on 1200 log-spaced times over full positive range',
    weight=weight,mean_fast_days=float(m1),mean_slow_days=float(m2),
    old=metrics(old),refitted=metrics(p),
    caveat='In-sample descriptive fit; dependence, zero delays and censoring not modelled. Not propagated to M2.')
(root/'Figures/timing_mixture_refit.json').write_text(json.dumps(result,indent=2)+'\n')
(root/'Figures/timing_mixture_refit.tex').write_text(
    '% Generated by scripts/refit_timing_mixture.py; fit to plotted full Railgun ECDF.\n'
    '\\addplot [thick, black, dashed, no marks, domain=-3:3.176091259,\n'
    '  samples=300, variable=\\u]\n'
    f'  ({{10^\\u}},{{{weight:.16g}*(1-exp(-10^\\u/{m1:.16g}))\n'
    f'    +{1-weight:.16g}*(1-exp(-10^\\u/{m2:.16g}))}});\n'
    '\\addlegendentry{Railgun two-exponential CDF fit}\n')
print(json.dumps(result,indent=2))
